### ISSUE TITLE
missing key "fight2"

### ISSUE THREAD

**Issue by cerisara** [upiterbarg/hihack#1]
I tried to generate the corpus with AutoAscend, but it immediately exists after the first step.
I tracked the error to line 333 of file autoascend_env_wrapper.py
where it's attempting to get HIHACK_ORDINALS[agent_strategy_log]
with agent_strategy_log=='fight2'
but there's no such key in HIHACK_ORDINALS

**Comment by upiterbarg** [comment]
Apologies, this is now fixed -- the `autoascend` submodule image here was not properly synced with the latest commit.
